[package]
name = "RustCLI"
version = "0.0.1"
description = "Rust CLI"
repository = "https://github.com/GuilhermeWerner/RustCLI"
authors = ["GuilhermeWerner <guilhermeqwerner@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[[bin]]
name="Console"
path = "Source/Console.rs"
